# Generated by Django 3.2.25 on 2024-11-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(default='', max_length=50),
        ),
    ]
