# Generated by Django 3.2.25 on 2024-11-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0002_smartphone_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='height',
            field=models.CharField(choices=[('S', 'Small'), ('B', 'Big')], default='S', max_length=1),
        ),
    ]
